In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB


# saving and loading the model
import joblib

In [2]:
vec = joblib.load("vec.pkl")
model = joblib.load("model.pkl")

c:\users\rohit khoiwal\appdata\local\programs\python\python37\lib\site-packages\sklearn\feature_extraction\image.py:167: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.int):
c:\users\rohit khoiwal\appdata\local\programs\python\python37\lib\site-packages\sklearn\base.py:253: UserWarning: Trying to unpickle estimator CountVectorizer from version 0.24.2 when using version 0.20.4. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
c:\users\rohit khoiwal\appdata\local\programs\python\python37\lib\site-pac

-   0   for Neutral
-   1   for Positive
-  -1   for Negative

In [3]:
model.predict(vec.transform(['I lost my job after the pandemic']))

array([-1], dtype=int64)

In [4]:
model.predict(vec.transform(['I get my job after the pandemic i am happy']))

array([1], dtype=int64)

In [5]:
model.predict(vec.transform(['I am sad']))

array([-1], dtype=int64)

In [6]:
model.predict(vec.transform(['I am happy']))

array([1], dtype=int64)

In [8]:
model.predict(vec.transform(['i lost my old job but found new job which is better']))

array([0], dtype=int64)